### PR TITLE
Strict coproduct

### PR DESCRIPTION
**Pull request by cchalmers**
I actually wrote this a while ago for a more efficient coproduct to use in a diagrams tree. In the small tests I did on benchmarking diagrams it actually make a small improvement so I think it's worth having.

### CODE REVIEW

**Comment by byorgey** [comment]
I tried restarting the travis builds that ran into API rate limits.

**Comment by cchalmers** [comment]
Hmm, that rate limiter's pretty annoying. Maybe we should start authenticating them?

[github's rate limit stuff](https://developer.github.com/v3/#rate-limiting)
[travis secret environment variables](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml)

**Comment by byorgey** [comment]
Yes, quite annoying.  Did they recently reduce the limits or something?  I don't remember this ever happening before.  

I've now created an OAuth authentication token for the diagrams github organization.  Unfortunately (1) we would have to add an encrypted version of this to the `.travis.yml` of every single diagrams repo which is annoying. (2) Even more annoying is this fine print from https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml: 

"Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code."

Pull requests from forks is exactly the scenario for which we are using the github API. =(

**Comment by byorgey** [comment]
I suppose this is yet another argument for using a single megarepo instead of a bunch of separate per-package repos like we have currently.

**Comment by byorgey** [comment]
I'm going to merge this; we can work out the travis issues separately.

**Pull request merged**
