### PR TITLE
Add missing instances for Inf.

### PR DESCRIPTION
**Pull request by merijn**
Replaces #30 without controversial Num instance.

### CODE REVIEW

**Comment by cchalmers** [comment]
Has a [build error](https://travis-ci.org/diagrams/monoid-extras/jobs/208616205) on `ghc-7.8`:

```
src/Data/Monoid/Inf.hs:98:10:
    Not in scope: type constructor or class ‘Applicative’
```

Other than that looks good to me.

**Comment by byorgey** [comment]
@merijn , could you just add a `Control.Applicative` import?  That should get it to compile with older versions of `base`.  I'm not too worried about the "unused import" warning on newer ones.  If we want to be really clever we could use some CPP but that might be more trouble than it's worth.

**Comment by merijn** [comment]
Added the import of Applicative(..), although I suppose I could also change it to not have the explicit import list...

**Comment by cchalmers** [comment]
There's still a small build error but I'll fix it. Thanks!

**Pull request merged**
